name: inglab_flutter_test
version: 1.0.0+1
publish_to: none
description: A mobile application created as an entry test for the Ingenious Lab company
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: any
  get: 4.6.6
  google_fonts: 5.1.0
  intl: 0.18.1
  pretty_dio_logger: 1.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

